// Private Pages
export { default as PRIVATE_ROUTE } from '../routes/PrivateRoute'

export { default as DASHBOARD } from '../pages/Dashboard'
export { default as ENQUIRIES } from '../pages/enquiryPage/Enquiries'
export { default as FEE_COLLECTION } from '../pages/feesPage/FeeCollection'
export { default as ADMISSIONS } from '../pages/admissionPage/Admissions'
export { default as NEW_ADMISSIONS } from '../pages/admissionPage/subPage/NewAdmission'
export { default as PASSOUT } from '../pages/passoutPage/Passout'
export { default as TOTAL_EMPLOYEES } from '../pages/totalEmployeePage/TotalEmpolyees'
export { default as LEAD_DISTRIBUTION } from '../pages/leadDistributionPage/LeadDistribution'
export { default as COURSES } from '../pages/coursesPage/Courses'
export { default as ADD_NEW_COURSE } from '../pages/coursesPage/subPage/AddNewCourse'
export { default as DEMO_CLASS } from '../pages/demoClassPage/DemoClasses'
export { default as PROFILE } from '../pages/profilePage/MyProfile'
export { default as EDIT_PROFILE } from '../pages/profilePage/subPage/EditProfile'
export { default as CHANGE_PASSWORD } from '../pages/profilePage/subPage/ChangePassword'
export { default as SUPPORT } from '../pages/Support'
export { default as ERROR } from '../pages/ErrorPage'
export { default as INVOICE } from '../pages/Invoice'

// Public Pages
export { default as LOGIN } from '../pages/Login'
export { default as FORGOT_PASSWORD } from '../pages/ForgotPassword'
export { default as VARIFY_OTP } from '../pages/VarifyOtp'